In [36]:
import numpy as np
import pandas as pd
#pip3 install opencv-python
import cv2
import csv
from os import path as osp
import os


In [37]:
def extract_image(filename,height,width):
    # print(filename)
    image = cv2.imread(filename)
    image = cv2.resize(image,(height,width))
    b,g,r = cv2.split(image)
    rgb_image = cv2.merge([r,g,b])

    return rgb_image

In [38]:
import tensorflow as tf

def read_pictures(file_list):
    file_queue = tf.train.string_input_producer(file_list)
    
    reader = tf.WholeFileReader()
    
    key, value = reader.read(file_queue)
    print("key " , key)
    print("value " , value)
    
    image = tf.image.decode_jpeg(value)
    print("image " , image)
    
    imageResized = tf.image.resize_images(image,[200,200])
    imageResized.set_shape(shape=[200,200,3])
    print("imageResized " , imageResized)
    
    image_batch = tf.train.batch([imageResized], batch_size=100,num_threads=1, capacity=100)
    
    with tf.Session() as sess:
        coord = tf.train.Coordinator()
        threads = tf.train.start_queue_runners(sess=sess, coord = coord)
        key_new,value_new,image_new, image_resizedNew = sess.run([key, value,image, imageResized])
        
        coord.request_stop()
        coord.join(threads)
    return None
    

In [39]:
rosesDir = "../data/images/roses/"
fileListRoses = os.listdir(rosesDir)

for eachFile in fileListRoses:
    print("processing file ", eachFile)
    fileRGB1 = extract_image(rosesDir + eachFile, 200,200)
    print("fileRGB1", fileRGB1)


processing file  2550860627_998a4fc4c1.jpg
fileRGB1 [[[126   0   1]
  [121   0   1]
  [114   1   1]
  ...
  [ 30  41  24]
  [ 40  50  27]
  [ 58  65  48]]

 [[123   0   0]
  [118   1   1]
  [110   0   0]
  ...
  [ 34  42  27]
  [ 33  41  20]
  [ 49  56  38]]

 [[121   0   0]
  [115   1   0]
  [108   1   1]
  ...
  [ 33  40  24]
  [ 35  42  26]
  [ 34  41  25]]

 ...

 [[130 138 145]
  [122 128 131]
  [ 81  87  74]
  ...
  [ 34  42  40]
  [ 37  43  41]
  [ 33  40  38]]

 [[138 144 152]
  [130 136 144]
  [ 95 100  91]
  ...
  [ 33  43  42]
  [ 36  43  42]
  [ 37  43  43]]

 [[150 154 161]
  [134 141 145]
  [ 97  99  95]
  ...
  [ 32  42  43]
  [ 37  46  46]
  [ 39  45  45]]]
processing file  4505921907_21c8002fde.jpg
fileRGB1 [[[192 118 146]
  [189 115 142]
  [188 114 141]
  ...
  [ 41  73  44]
  [ 39  71  43]
  [ 39  72  43]]

 [[193 118 148]
  [191 116 146]
  [190 116 143]
  ...
  [ 38  72  44]
  [ 38  71  42]
  [ 38  71  42]]

 [[194 120 150]
  [192 117 147]
  [192 116 147]
  ...
  [ 

In [40]:
rosesDir = "../data/images/roses/"
fileListRoses = os.listdir(rosesDir)

file_list = [os.path.join(rosesDir, file) for file in fileListRoses]
print("file_list", file_list)

file_list ['../data/images/roses/2550860627_998a4fc4c1.jpg', '../data/images/roses/4505921907_21c8002fde.jpg', '../data/images/roses/16424992340_c1d9eb72b4.jpg', '../data/images/roses/6347846687_3f0a7c3176.jpg', '../data/images/roses/6347846935_51e3dc2481_n.jpg', '../data/images/roses/6347847065_83cf87333b_n.jpg']


In [41]:
read_pictures(file_list)

key  Tensor("ReaderReadV2_2:0", shape=(), dtype=string)
value  Tensor("ReaderReadV2_2:1", shape=(), dtype=string)
image  Tensor("DecodeJpeg_2:0", shape=(?, ?, ?), dtype=uint8)
imageResized  Tensor("resize_2/Squeeze:0", shape=(200, 200, 3), dtype=float32)
