In [5]:
import torch
import numpy as np
from torch.autograd import Variable 

 
np_data = np.arange(6).reshape((2, 3))
torch_data = torch.from_numpy(np_data)

print(torch_data)

data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data) 
print(tensor)

tensor = torch.FloatTensor([[1,2],[3,4]])
variable = Variable(tensor, requires_grad=True)
print(variable)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([-1., -2.,  1.,  2.])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [6]:
import torch.nn.functional as F     # 激励函数都在这
from torch.autograd import Variable

# 做一些假数据来观看图像
x = torch.linspace(-5, 5, 200)  # x data (tensor), shape=(100, 1)
x = Variable(x)


x_np = x.data.numpy()   # 换成 numpy array, 出图时用
 
# 几种常用的 激励函数
y_relu = F.relu(x).data.numpy()
y_sigmoid = F.sigmoid(x).data.numpy()
y_tanh = F.tanh(x).data.numpy()
y_softplus = F.softplus(x).data.numpy()
print(y_softplus)
# y_softmax = F.softmax(x)  softmax 比较特殊, 不能直接显示, 不过他是关于概率的, 用于分类

[0.00671535 0.00706021 0.00742271 0.00780375 0.00820427 0.00862527
 0.00906776 0.00953285 0.01002167 0.01053544 0.01107538 0.01164285
 0.01223921 0.01286592 0.0135245  0.01421656 0.01494376 0.01570788
 0.01651074 0.01735429 0.01824053 0.01917161 0.02014973 0.02117724
 0.02225655 0.02339024 0.02458096 0.02583152 0.02714485 0.028524
 0.02997218 0.03149272 0.03308915 0.03476509 0.03652439 0.03837101
 0.04030914 0.04234309 0.04447743 0.04671685 0.04906628 0.05153086
 0.0541159  0.05682698 0.05966987 0.06265058 0.06577535 0.06905065
 0.07248322 0.07608002 0.07984827 0.08379547 0.08792935 0.09225792
 0.09678947 0.10153248 0.10649578 0.11168842 0.11711974 0.12279933
 0.12873703 0.13494292 0.14142737 0.14820093 0.15527444 0.1626589
 0.17036554 0.1784058  0.18679126 0.19553366 0.20464492 0.21413702
 0.22402205 0.23431218 0.24501958 0.25615656 0.26773518 0.27976757
 0.29226583 0.30524188 0.3187074  0.33267394 0.34715295 0.3621552
 0.3776917  0.39377248 0.41040778 0.4276069  0.44537872 0.4637321


/usr/local/python36/lib/python3.6/site-packages/torch/nn/functional.py:1350: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/usr/local/python36/lib/python3.6/site-packages/torch/nn/functional.py:1339: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
