In [1]:
#https://github.com/zergtant/pytorch-handbook/blob/master/chapter1/1_tensor_tutorial.ipynb
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[-2.1761e+37,  4.5579e-41, -2.1761e+37],
        [ 4.5579e-41,         nan,  0.0000e+00],
        [ 1.7753e+28,  4.4339e+27,  1.3848e-14],
        [ 6.8801e+16,  1.8370e+25,  1.4603e-19],
        [ 6.8794e+11,  2.7253e+20,  3.0866e+29]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2883, 0.9890, 0.3155],
        [0.3138, 0.5414, 0.3714],
        [0.5312, 0.1081, 0.1315],
        [0.7028, 0.0821, 0.4086],
        [0.9972, 0.2165, 0.1904]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = torch.rand(5,3)
y = torch.rand(5, 3)
print(x + y)
print(torch.add(x, y))

tensor([[1.1053, 1.2099, 1.0610],
        [1.4760, 0.8279, 1.9108],
        [1.7749, 0.7129, 1.0750],
        [1.5134, 1.0996, 1.1305],
        [0.9024, 0.4352, 1.1517]])
tensor([[1.1053, 1.2099, 1.0610],
        [1.4760, 0.8279, 1.9108],
        [1.7749, 0.7129, 1.0750],
        [1.5134, 1.0996, 1.1305],
        [0.9024, 0.4352, 1.1517]])


In [10]:
print(x)
print(x[:, 1])

#view: just like reshape of numpy
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  #  size -1 从其他维度推断
print(x.size(), y.size(), z.size())

tensor([[0.2911, 0.8049, 0.6788],
        [0.8887, 0.4451, 0.9714],
        [0.8104, 0.4748, 0.7871],
        [0.7358, 0.3055, 0.4877],
        [0.6016, 0.1489, 0.4157]])
tensor([0.8049, 0.4451, 0.4748, 0.3055, 0.1489])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [11]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

import numpy as np
a = np.ones(5)

#from numpy get a tensor
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)



tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [12]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA 设备对象
    y = torch.ones_like(x, device=device)  # 直接从GPU创建张量
    x = x.to(device)                       # 或者直接使用``.to("cuda")``将张量移动到cuda中
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 也会对变量的类型做更改