In [7]:
#My own logistic regression implementation
#https://blog.csdn.net/Joker_sir5/article/details/82531211
#https://www.cnblogs.com/VitoLin21/p/11395753.html
import numpy as np
from sklearn.metrics import accuracy_score

class LogisticRegression:
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
        self._theta = None
    
    def _sigmoid(self, t):
        return 1. / (1. + np.exp(-t))
    
    def fit(self, X_train, y_train, eta=0.01, n_iters=1e4):
        def J(theta, X_b, y):
            y_hat = self._sigmoid(X_b.dot(theta))
            try:
                return - np.sum(y*np.log(y_hat) + (1-y)*np.log(1-y_hat)) / len(y)
            except:
                return float('inf')

        def dJ(theta, X_b, y):
            return X_b.T.dot(self._sigmoid(X_b.dot(theta)) - y) / len(X_b)

        def gradient_descent(X_b, y, initial_theta, eta, n_iters=100, epsilon=1e-8):
            theta = initial_theta
            cur_iter = 0
            while cur_iter < n_iters:
                gradient = dJ(theta, X_b, y)
                last_theta = theta
                theta = theta - eta * gradient
                
                delta = abs(J(theta, X_b, y) - J(last_theta, X_b, y))
                if (delta < epsilon) :
                    break
                if (cur_iter % 10 ==0) :
                    print("iteration  " + str(cur_iter))
                    print(theta)
                    print("delta " + str(delta))
                cur_iter += 1
            return theta

        X_b = np.hstack([np.ones((len(X_train), 1)), X_train])
        initial_theta = np.zeros(X_b.shape[1])
        self._theta = gradient_descent(X_b, y_train, initial_theta, eta, n_iters)

        self.intercept_ = self._theta[0]
        self.coef_ = self._theta[1:]
        return self

    def predict_proba(self, X_predict):
        X_b = np.hstack([np.ones((len(X_predict), 1)), X_predict])
        return self._sigmoid(X_b.dot(self._theta))

    def predict(self, X_predict):
        proba = self.predict_proba(X_predict)
        return np.array(proba >= 0.5, dtype='int')

    def score(self, X_test, y_test):
        y_predict = self.predict(X_test)
        return accuracy_score(y_test, y_predict)
    

In [8]:
from sklearn.datasets import load_iris
iris = load_iris() 
X = iris.data
y = iris.target
X = X[y < 2, :2]
y = y[y < 2]
print(X)
print(y)

[[5.1 3.5]
 [4.9 3. ]
 [4.7 3.2]
 [4.6 3.1]
 [5.  3.6]
 [5.4 3.9]
 [4.6 3.4]
 [5.  3.4]
 [4.4 2.9]
 [4.9 3.1]
 [5.4 3.7]
 [4.8 3.4]
 [4.8 3. ]
 [4.3 3. ]
 [5.8 4. ]
 [5.7 4.4]
 [5.4 3.9]
 [5.1 3.5]
 [5.7 3.8]
 [5.1 3.8]
 [5.4 3.4]
 [5.1 3.7]
 [4.6 3.6]
 [5.1 3.3]
 [4.8 3.4]
 [5.  3. ]
 [5.  3.4]
 [5.2 3.5]
 [5.2 3.4]
 [4.7 3.2]
 [4.8 3.1]
 [5.4 3.4]
 [5.2 4.1]
 [5.5 4.2]
 [4.9 3.1]
 [5.  3.2]
 [5.5 3.5]
 [4.9 3.6]
 [4.4 3. ]
 [5.1 3.4]
 [5.  3.5]
 [4.5 2.3]
 [4.4 3.2]
 [5.  3.5]
 [5.1 3.8]
 [4.8 3. ]
 [5.1 3.8]
 [4.6 3.2]
 [5.3 3.7]
 [5.  3.3]
 [7.  3.2]
 [6.4 3.2]
 [6.9 3.1]
 [5.5 2.3]
 [6.5 2.8]
 [5.7 2.8]
 [6.3 3.3]
 [4.9 2.4]
 [6.6 2.9]
 [5.2 2.7]
 [5.  2. ]
 [5.9 3. ]
 [6.  2.2]
 [6.1 2.9]
 [5.6 2.9]
 [6.7 3.1]
 [5.6 3. ]
 [5.8 2.7]
 [6.2 2.2]
 [5.6 2.5]
 [5.9 3.2]
 [6.1 2.8]
 [6.3 2.5]
 [6.1 2.8]
 [6.4 2.9]
 [6.6 3. ]
 [6.8 2.8]
 [6.7 3. ]
 [6.  2.9]
 [5.7 2.6]
 [5.5 2.4]
 [5.5 2.4]
 [5.8 2.7]
 [6.  2.7]
 [5.4 3. ]
 [6.  3.4]
 [6.7 3.1]
 [6.3 2.3]
 [5.6 3. ]
 [5.5 2.5]
 [5.5 2.6]

In [9]:
logisticRegression = LogisticRegression();
logisticRegression.fit(X, y)

iteration  0
[ 0.        0.002325 -0.001645]
delta 0.0008034906553913146
iteration  10
[-0.00078246  0.02116331 -0.0204464 ]
delta 0.0006711140333973686
iteration  20
[-0.00227126  0.03593654 -0.04129785]
delta 0.0006464480929274652
iteration  30
[-0.00399332  0.04925823 -0.06273038]
delta 0.0006344341906949769
iteration  40
[-0.00578758  0.06201903 -0.08424466]
delta 0.0006240425409901329
iteration  50
[-0.00759918  0.07452316 -0.10567146]
delta 0.0006139905089332931
iteration  60
[-0.00940949  0.08687495 -0.1269541 ]
delta 0.0006041277880223239
iteration  70
[-0.01121221  0.09911059 -0.14807427]
delta 0.000594435615084099
iteration  80
[-0.01300526  0.111243   -0.16902677]
delta 0.0005849104232303892
iteration  90
[-0.014788    0.12327719 -0.18981089]
delta 0.0005755503300488574
iteration  100
[-0.01656027  0.13521547 -0.21042744]
delta 0.0005663535792067576
iteration  110
[-0.01832209  0.14705921 -0.23087775]
delta 0.0005573183678151405
iteration  120
[-0.02007352  0.15880948 -0.251